# Generated by Django 4.2.18 on 2025-01-31 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to=settings.AUTH_USER_MODEL),
        ),
    ]
