# Generated by Django 4.2.18 on 2025-03-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='read',
            new_name='sent',
        ),
        migrations.AddField(
            model_name='notification',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='large_icon',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='schedule_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='segment',
            field=models.CharField(default='Total Subscriptions', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='url_action',
            field=models.URLField(blank=True, null=True),
        ),
    ]
