# Generated by Django 4.2.18 on 2025-03-08 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0007_rename_read_notification_sent_notification_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeAvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='administration.avis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'avis')},
            },
        ),
    ]
