# Generated by Django 4.2.18 on 2025-03-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pays',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sexe',
            field=models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ville',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
