# Generated by Django 4.2.18 on 2025-02-01 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_user_contact_user_nom_user_prenom_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeToBe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btb_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('btob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='public.betobe')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('participant', 'btob')},
            },
        ),
    ]
