# Generated by Django 4.2.18 on 2025-02-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_visitcounter_city_visitcounter_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('participant', 'Participant'), ('exposant', 'Exposant'), ('sponsor', 'Sponsor'), ('media', 'Media'), ('organisateur', 'Organisateur')], max_length=20, null=True),
        ),
    ]
