# Generated by Django 4.2.18 on 2025-03-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_user_pays_user_sexe_user_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo_profile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
