# Generated by Django 4.2.18 on 2025-02-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_user_civilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fonction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
