# Generated by Django 4.2.18 on 2025-02-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_user_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='miniature',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
